### PR TITLE
Add frosted backgrounds and a menu to test it on

### PR DESCRIPTION
**Pull request by AdaRoseCannon**
This adds two new features,

1. A menu
1. Frosted backgrounds

Documentation for both of these will come in a PR which merges the documentation into the main repo

recording4

### CODE REVIEW

**Comment by AdaRoseCannon** [comment]
Here is the HTML code for the menu:

```

            <span role="button" tabindex="0" aria-haspopup="true" aria-controls="oui-demo-menu2" class="oui-button oui-menu-trigger" style="float:right;">menu
                <ul id="oui-demo-menu2" role="menu" class="oui-menu oui-bubble oui-frosted oui-menu-direction-up oui-menu-direction-left">
                    <li role="none" class="oui-bubble-item"><a role="menuitem" href="#">Menu Item 1</a></li>
                    <li role="none" class="oui-bubble-item"><a role="menuitem" href="#">A 2nd item</a></li>
                    <li role="none" class="oui-bubble-item"><a role="menuitem" href="#">Third item</a></li>
                </ul>
            </span>
```

You can test it by running a local http server and opening `http://localhost:8080/tests/demos/image.html`

**Comment by AdaRoseCannon** [comment]
This still needs some JS to complete the A11y requirements, see: https://www.w3.org/TR/wai-aria-practices-1.1/examples/menu-button/menu-button-links.html

Perhaps this should be an included JS file the developer can require or perhaps it should be a list of things the implementer will need to implement in addition.

**Comment by AdaRoseCannon** [comment]
Update: recording4

**Comment by AdaRoseCannon** [comment]
New HTML uses details element for correct tap-to-open behaviour as prescribed by Aria

```
<details class="oui-menu" role="none">
	<summary role="button" tabindex="0" aria-haspopup="true" aria-controls="oui-demo-menu" class="oui-button oui-menu-trigger">
		menu
	</summary>
	<ul id="oui-demo-menu" tabindex="0" role="menu" class="oui-bubble oui-frosted">
		<li role="none" class="oui-overlay-bubble-item">
			<a role="menuitem" href="#">Menu Item 1</a>
		</li>
		<li role="none" class="oui-overlay-bubble-item">
			<a role="menuitem" href="#">A 2nd item</a>
		</li>
		<li role="none" class="oui-overlay-bubble-item">
			<a role="menuitem" href="#">Third item</a>
		</li>
		<li role="none" class="oui-overlay-bubble-item">
			<a role="menuitem" href="#">The last item</a>
		</li>
	</ul>
</details>
```

**Comment by AdaRoseCannon** [comment]
I've added the menu documentation

**Comment by PicchiKevin** [comment]
Can you add a link to this doc in the sidebar so we can navigate to it.

Here is also what I see in the docs:  
image

I'd recommend creating an example(inside /docs/examples) and including it inside the page.
Like this for example: https://raw.githubusercontent.com/SamsungInternet/OneUI-Web/master/docs/components/badges.md

Or having a good quality GIF would be an other acceptable solution.

CSS looks good, will merge once the above point is fixed.

**Review by PicchiKevin — CHANGES_REQUESTED** [review]
Can you add a link to this doc in the sidebar so we can navigate to it.

Here is also what I see in the docs:  
image

I'd recommend creating an example(inside /docs/examples) and including it inside the page.
Like this for example: https://raw.githubusercontent.com/SamsungInternet/OneUI-Web/master/docs/components/badges.md

Or having a good quality GIF would be an other acceptable solution.

CSS looks good, will merge once the above point is fixed.

**Review by PicchiKevin — APPROVED** [review]

**Comment by PicchiKevin** [comment]
Looks good to me!

**Pull request merged**
