### PR TITLE
Github workflow for testing accessibility

### PR DESCRIPTION
**Pull request by AdaRoseCannon**

### CODE REVIEW

**Comment by AdaRoseCannon** [comment]
This check failed. It doesn't show that it did.

**Comment by AdaRoseCannon** [comment]
Tests now fail for the correct reason, check out the details.

**Comment by PicchiKevin** [comment]
looks nice, 100 error to go :)

**Comment by AdaRoseCannon** [comment]
@PicchiKevin I think we should probably merge this then, work on fixing the 100 errors lol. 

It would probably also be worth doing it in the `master` branch as well with a test.html file.

**Comment by PicchiKevin** [comment]
**Merged** thanks for your help, it would be cool if it could review the code from pull requests and add comments to lines containing accessibility errors.

**Pull request merged**
